/**
 * The landing page's media catalogue.
 *
 * Every file under /public/media is original artwork generated by
 * `scripts/generate-media.mjs` — layered gradient meshes, grain and hand-built
 * vector scenes. Nothing is third-party stock, so there is no licence to track.
 *
 * `swapHint` records what real creator photography should replace each tile
 * with once it is available; the layout is built to take a photo at the same
 * aspect ratio without any code change.
 */

export type MediaKind = "Reel" | "Video" | "Photo" | "Podcast" | "Thumbnail" | "Brand Kit" | "Script";

export interface MediaItem {
  src: string;
  /** Intrinsic size, so the browser can reserve space and avoid layout shift. */
  width: number;
  height: number;
  kind: MediaKind;
  alt: string;
  /** Shown as a duration chip on video and audio tiles. */
  meta?: string;
  swapHint: string;
}

export const CONTENT_WALL: MediaItem[] = [
  {
    src: "/media/reel-01.webp",
    width: 540,
    height: 960,
    kind: "Reel",
    alt: "Illustration of a creator filming a vertical video on a phone",
    meta: "0:28",
    swapHint: "Vertical 9:16 photo of a creator filming themselves on a phone",
  },
  {
    src: "/media/video-01.webp",
    width: 960,
    height: 540,
    kind: "Video",
    alt: "Illustration of a creator editing a video timeline at a desk",
    meta: "12:04",
    swapHint: "16:9 photo of a creator editing footage on a laptop",
  },
  {
    src: "/media/photo-01.webp",
    width: 720,
    height: 720,
    kind: "Photo",
    alt: "Illustration of a photographer raising a camera",
    swapHint: "Square photo from a real shoot — portrait or product",
  },
  {
    src: "/media/podcast-01.webp",
    width: 720,
    height: 720,
    kind: "Podcast",
    alt: "Illustration of a creator recording into a microphone",
    meta: "41:17",
    swapHint: "Square photo of a podcast recording setup",
  },
  {
    src: "/media/reel-02.webp",
    width: 540,
    height: 960,
    kind: "Reel",
    alt: "Illustration of a travel creator holding a camera",
    meta: "0:45",
    swapHint: "Vertical 9:16 travel or lifestyle content still",
  },
  {
    src: "/media/thumbnail-01.webp",
    width: 960,
    height: 540,
    kind: "Thumbnail",
    alt: "Illustration of a grid of video thumbnail artwork",
    swapHint: "16:9 grid of real thumbnail artwork",
  },
  {
    src: "/media/brand-01.webp",
    width: 720,
    height: 720,
    kind: "Brand Kit",
    alt: "Illustration of brand kit tiles",
    swapHint: "Square flat-lay of brand assets, logos or a media kit",
  },
  {
    src: "/media/script-01.webp",
    width: 720,
    height: 960,
    kind: "Script",
    alt: "Illustration of a script document",
    swapHint: "Vertical shot of a script, caption sheet or content plan",
  },
  {
    src: "/media/reel-03.webp",
    width: 540,
    height: 960,
    kind: "Reel",
    alt: "Illustration of a creator filming in a studio",
    meta: "1:02",
    swapHint: "Vertical 9:16 studio or behind-the-scenes still",
  },
  {
    src: "/media/video-02.webp",
    width: 960,
    height: 540,
    kind: "Video",
    alt: "Illustration of a creator shooting with a camera",
    meta: "06:39",
    swapHint: "16:9 photo of a shoot in progress",
  },
  {
    src: "/media/photo-02.webp",
    width: 720,
    height: 720,
    kind: "Photo",
    alt: "Illustration of a creator working on brand content",
    swapHint: "Square product or brand-content photo",
  },
  {
    src: "/media/studio-01.webp",
    width: 960,
    height: 540,
    kind: "Podcast",
    alt: "Illustration of a studio recording session",
    meta: "22:51",
    swapHint: "16:9 photo of a studio or recording session",
  },
];

/** The three tiles that float beside the hero. */
export const HERO_TILES = [
  CONTENT_WALL[0]!,
  CONTENT_WALL[3]!,
  CONTENT_WALL[1]!,
];
