/**
 * Downloads, optimises and credits real creator photography.
 *
 * The landing page currently ships original generated artwork because stock
 * libraries were unreachable. This script is the swap path: fill in the URLs in
 * scripts/photo-manifest.json, run it, and every tile is replaced with a real
 * photograph at the right aspect ratio, with licence provenance recorded.
 *
 * Run:  node scripts/ingest-photos.mjs
 * Out:  public/media/photos/*.webp  and  public/media/CREDITS.md
 *
 * Nothing here invents a source. An entry with no `url` is skipped and
 * reported, so a partial manifest degrades to a partial swap rather than a
 * broken page.
 */

import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

const MANIFEST = path.resolve("scripts/photo-manifest.json");
const OUT_DIR = path.resolve("public/media/photos");
const CREDITS = path.resolve("public/media/CREDITS.md");

/** Longest edge we ever render a tile at, doubled for high-DPI screens. */
const MAX_EDGE = 1280;

async function download(url) {
  const response = await fetch(url, { redirect: "follow" });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }
  const type = response.headers.get("content-type") ?? "";
  if (!type.startsWith("image/")) {
    throw new Error(`expected an image, got "${type}"`);
  }
  return Buffer.from(await response.arrayBuffer());
}

/**
 * Crop to the tile's aspect ratio rather than letterboxing, using attention
 * cropping so a person stays in frame instead of being sliced by a centre cut.
 */
async function optimise(buffer, { width, height }) {
  const scale = Math.min(1, MAX_EDGE / Math.max(width, height));
  return sharp(buffer)
    .resize({
      width: Math.round(width * scale),
      height: Math.round(height * scale),
      fit: "cover",
      position: sharp.strategy.attention,
    })
    .webp({ quality: 72, effort: 6 })
    .toBuffer();
}

async function main() {
  const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
  await mkdir(OUT_DIR, { recursive: true });

  const done = [];
  const skipped = [];
  const failed = [];

  for (const entry of manifest.photos) {
    if (!entry.url) {
      skipped.push(entry);
      continue;
    }
    try {
      const raw = await download(entry.url);
      const optimised = await optimise(raw, entry);
      await writeFile(path.join(OUT_DIR, `${entry.id}.webp`), optimised);
      done.push({ ...entry, bytes: optimised.length });
      console.log(`  ${entry.id}.webp`.padEnd(28), `${(optimised.length / 1024).toFixed(1)} KB`);
    } catch (error) {
      failed.push({ entry, message: error instanceof Error ? error.message : String(error) });
      console.error(`  ${entry.id}: FAILED — ${error}`);
    }
  }

  if (done.length > 0) {
    const lines = [
      "# Image credits",
      "",
      "Photography used on the Creator Vault landing page.",
      "Generated by `scripts/ingest-photos.mjs` — do not edit by hand.",
      "",
      "| File | Source | Licence | Credit |",
      "| --- | --- | --- | --- |",
      ...done.map(
        (d) =>
          `| \`photos/${d.id}.webp\` | [${d.source}](${d.pageUrl ?? d.url}) | ${d.license} | ${d.credit ?? "—"} |`,
      ),
      "",
      "> Stock licences cover editorial and commercial use of the photograph, but",
      "> they do not by themselves grant a model release for every use of an",
      "> identifiable person. Before launch, confirm each photo of a recognisable",
      "> person is cleared for marketing use, or prefer shots where faces are not",
      "> the identifying feature.",
      "",
    ];
    await writeFile(CREDITS, lines.join("\n"));
  }

  console.log(
    `\n${done.length} imported, ${skipped.length} awaiting a URL, ${failed.length} failed`,
  );
  if (skipped.length > 0) {
    console.log("Awaiting URLs:");
    for (const entry of skipped) {
      console.log(`  ${entry.id.padEnd(16)} ${entry.width}x${entry.height}  ${entry.brief}`);
    }
  }
  if (failed.length > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
